### ISSUE TITLE
Should returnPromiseOnSuspend always return a Promise

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/js-promise-integration#4] opened 2022-05-13 19:01 UTC
`returnPromiseOnSuspend` is specified to either:

1. Return a Promise if the wrapped export eventually was suspended
2. Return the results of the wrapped export

If the wrapped export itself returns a Promise, it's not possible to tell whether the wrapped export was suspended or if it returned normally. This is definitely a corner case, so I don't know whether it's a real issue or not.

An alternative would be to returned `Promise.resolve(wrappedExportResults)` in the case the wrapped export returns normally.

**Comment by RossTate** [comment] 2022-05-16 17:11
My recollection of when we discussed the alternative you suggested is that it's easier for the user of the module to apply `Promise.resolve` to the export themselves than it would be for the user to "undo" always applying `Promise.resolve` in the exported function should they want the more direct/unflattened behavior.

**Comment by fgmccabe** [comment] 2022-10-06 22:31
Closing as its a duplicate of another issue. wrapped exports will always return a Promise; but a future version may allow programmer to specify a different behavior.

**Closed by fgmccabe** 2022-10-06 22:31 UTC
